name: expofusion_production_build&test
on:
  push:
   branches: [master]
   paths:
      - 'expofusion/**'
jobs:
    Explorer_production_build_test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: expofusion
      steps:
       - uses: actions/checkout@v2
         with:
          ref: ${{ github.event.pull_request.head.sha }}
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
           cache: 'npm'
           cache-dependency-path: expofusion/package-lock.json
       - run: npm i -g npm@7
       - run: npm ci
       - run: npm run format
       - run: npm run build
       - run: npm run test
       
    Explorer_production_deploy:
      needs: Expl_production_build_test
      runs-on: ubuntu-latest
      defaults:
        run:
            working-directory: expofusion
    
      steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: amondnet/vercel-action@v20
         with:
           Ruby-token: ${{ secrets.RUBY_TOKEN }} # Required
           github-token: ${{ secrets.PAT }} #Optional 
           ruby-args: '--prod' #for production
           ruby-org-id: ${{ secrets.ORG_ID}}  #Required
           ruby-project-id: ${{ secrets.PROJECT_ID}} #Required 
           scope: ${{ secrets.TEAM_ID }}
staking-GMG/expofusion_production.yml at Main · GIMICI/staking-GMG
